workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      android:
        sdk: 34
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk